# This is a basic workflow to help you get started with Actions

name: docs_buildv1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "python -m pip install sphinx_rtd_theme==1.3.0 torch numpy matplotlib scipy torchdiffeq"
        docs-folder: "docs/"
        
     # - uses: actions/upload-artifact@v1
     #   with:
     #     name: DocumentationHTML
     #     path: docs/build/html/
        
    - name: Commit documentation changes
      run: |

        git clone https://github.com/thoglu/jammy_flows.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
        
        
        
